# Generated by Django 5.2 on 2025-04-08 19:08

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


def clear_country_data(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.all().update(country=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # First clear the country data
        migrations.RunPython(clear_country_data),
        # Then change the field type
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MEM', 'Member'), ('ADM', 'Admin'), ('FS', 'Financial Secretary')], default='MEM', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('SUS', 'Suspended'), ('REM', 'Removed')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
