# Generated by Django 5.2 on 2025-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADM', 'Admin'), ('FS', 'Financial Secretary'), ('MEM', 'Member')], default='MEM', max_length=3),
        ),
    ]
